// GENERATED by designmd from DESIGN.md (frontmatter sha256 8bb8f8e6a938) — edit DESIGN.md, then re-export
export const colors = {
  "error": "\u001b[31m",
  "warning": "\u001b[33m",
  "info": "\u001b[36m",
  "success": "\u001b[32m",
  "muted": "\u001b[2m"
} as const;
export const reset = "\u001b[0m";
export type Role = keyof typeof colors;

const disabled = (): boolean =>
  Boolean(process.env.NO_COLOR) || process.argv.includes("--no-color");

export function paint(text: string, role: Role): string {
  if (disabled()) return text;
  return `${colors[role]}${text}${reset}`;
}
